include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_use_package_imports: true
    annotate_overrides: true
    prefer_final_fields: true
    prefer_const_constructors: true

analyzer:
  errors:
    avoid_print: error
    prefer_single_quotes: error
    always_use_package_imports: error
    annotate_overrides: error
    prefer_final_fields: error
    prefer_const_constructors: error