name: Danger

on:
  pull_request:
    branches:
      - main

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v1

      - name: Setup dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install Danger-js
        run: npm install -g danger
    
      - name: Activate command
        run: dart pub global activate
    
      - name: Run danger ci
        run: danger_dart ci
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}