name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Generate Resources
        run: flutter gen-l10n
        
      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Check component coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage-files: '{"lib/domain/**": 85, "lib/ui/**": 60}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Analyze
        run: dart analyze

      - name: Build APK
        run: flutter build apk --debug
