name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: ./.github/actions/setup-flutter

      - name: Generate Resources
        run: flutter gen-l10n

      - name: Install dependencies - Snapshot testes
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev liblzma-dev libglu1-mesa-dev

      - name: Run tests
        run: flutter test

      - name: Analyze
        run: dart analyze

      - name: Build APK
        run: flutter build apk --debug
